In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data=pd.read_csv('/content/sample.csv.csv')
print (data)
 



   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
x=data.iloc[:,:-1].values
y=data.iloc[:,3].values

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder  

label_encoder_x= LabelEncoder()  

x[:, 0]= label_encoder_x.fit_transform(x[:, 0])

In [ ]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder  

label_encoder_x= LabelEncoder()  

x[:, 2]= label_encoder_x.fit_transform(x[:, 0]) 

In [ ]:
x

array([[0, 44.0, 0],
       [2, 27.0, 2],
       [1, 30.0, 1],
       [2, 38.0, 2],
       [1, 40.0, 1],
       [0, 35.0, 0],
       [2, nan, 2],
       [0, 48.0, 0],
       [1, 50.0, 1],
       [0, 37.0, 0]], dtype=object)

In [ ]:
labelencoder_y= LabelEncoder()  

y= labelencoder_y.fit_transform(y) 

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
x[:,1:3]=imp.fit_transform(x[:,1:3])

In [ ]:
x

array([[0, 44.0, 0.0],
       [2, 27.0, 2.0],
       [1, 30.0, 1.0],
       [2, 38.0, 2.0],
       [1, 40.0, 1.0],
       [0, 35.0, 0.0],
       [2, 38.77777777777778, 2.0],
       [0, 48.0, 0.0],
       [1, 50.0, 1.0],
       [0, 37.0, 0.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE= LabelEncoder()
x[:,0]=LE.fit_transform(x[:,0])

In [ ]:
y= LE.fit_transform(y)

In [ ]:
x

array([[0, 44.0, 0.0],
       [2, 27.0, 2.0],
       [1, 30.0, 1.0],
       [2, 38.0, 2.0],
       [1, 40.0, 1.0],
       [0, 35.0, 0.0],
       [2, 38.77777777777778, 2.0],
       [0, 48.0, 0.0],
       [1, 50.0, 1.0],
       [0, 37.0, 0.0]], dtype=object)

In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.preprocessing import OneHotEncoder  
from sklearn.compose import ColumnTransformer
transform=ColumnTransformer([("norm1",OneHotEncoder(),[0])],remainder='passthrough')
x=transform.fit_transform(x)

In [ ]:
x

array([[1.0, 0.0, 0.0, 44.0, 0.0],
       [0.0, 0.0, 1.0, 27.0, 2.0],
       [0.0, 1.0, 0.0, 30.0, 1.0],
       [0.0, 0.0, 1.0, 38.0, 2.0],
       [0.0, 1.0, 0.0, 40.0, 1.0],
       [1.0, 0.0, 0.0, 35.0, 0.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 2.0],
       [1.0, 0.0, 0.0, 48.0, 0.0],
       [0.0, 1.0, 0.0, 50.0, 1.0],
       [1.0, 0.0, 0.0, 37.0, 0.0]], dtype=object)

In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train

array([[0.0, 1.0, 0.0, 40.0, 1.0],
       [1.0, 0.0, 0.0, 37.0, 0.0],
       [0.0, 0.0, 1.0, 27.0, 2.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 2.0],
       [1.0, 0.0, 0.0, 48.0, 0.0],
       [0.0, 0.0, 1.0, 38.0, 2.0],
       [1.0, 0.0, 0.0, 44.0, 0.0],
       [1.0, 0.0, 0.0, 35.0, 0.0]], dtype=object)

In [ ]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
x_train[:,3:5]=SC.fit_transform(x_train[:,3:5])

In [ ]:
x_train

array([[0.0, 1.0, 0.0, 0.2630675731713538, 0.13483997249264842],
       [1.0, 0.0, 0.0, -0.25350147960148617, -0.9438798074485389],
       [0.0, 0.0, 1.0, -1.9753983221776195, 1.2135597524338357],
       [0.0, 0.0, 1.0, 0.05261351463427101, 1.2135597524338357],
       [1.0, 0.0, 0.0, 1.6405850472322605, -0.9438798074485389],
       [0.0, 0.0, 1.0, -0.08131179534387283, 1.2135597524338357],
       [1.0, 0.0, 0.0, 0.9518263102018072, -0.9438798074485389],
       [1.0, 0.0, 0.0, -0.5978808481167128, -0.9438798074485389]],
      dtype=object)

In [ ]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])